"""change_template_status_to_string

Revision ID: 5b225e8d844c
Revises: 75be01f623d1
Create Date: 2025-11-26 11:51:06.082589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b225e8d844c'
down_revision = '75be01f623d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###