"""add_draft_tables

Revision ID: 9fd3e8d1bc1e
Revises: 20251130102953
Create Date: 2025-11-30 14:05:07.751728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fd3e8d1bc1e'
down_revision = '20251130102953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_draft_versions_draft_id', table_name='draft_versions')
    op.drop_index('ix_draft_versions_version_number', table_name='draft_versions')
    op.drop_table('draft_versions')
    op.add_column('drafts', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('drafts', sa.Column('format', sa.String(length=50), nullable=False))
    op.add_column('drafts', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('drafts', sa.Column('stage', sa.Enum('EDITING', 'REVIEW', 'FINAL', 'PUBLISHED', 'ARCHIVED', name='draftstage'), nullable=False))
    op.add_column('drafts', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.drop_index('ix_drafts_template_user', table_name='drafts')
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.drop_constraint('drafts_ibfk_2', 'drafts', type_='foreignkey')
    op.drop_constraint('fk_drafts_current_version', 'drafts', type_='foreignkey')
    op.drop_constraint('drafts_ibfk_1', 'drafts', type_='foreignkey')
    op.create_foreign_key(None, 'drafts', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'drafts', 'users', ['user_id'], ['id'])
    op.drop_column('drafts', 'editing_stage')
    op.drop_column('drafts', 'current_version_id')
    op.alter_column('reports', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='报告标题',
               existing_nullable=False)
    op.alter_column('reports', 'template_id',
               existing_type=mysql.INTEGER(),
               comment='使用的模板ID',
               existing_nullable=False)
    op.alter_column('reports', 'data_file_id',
               existing_type=mysql.INTEGER(),
               comment='数据文件ID',
               existing_nullable=True)
    op.alter_column('reports', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('reports', 'content',
               existing_type=mysql.JSON(),
               comment='报告内容',
               existing_nullable=True)
    op.alter_column('reports', 'full_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='完整报告文本',
               existing_nullable=True)
    op.alter_column('reports', 'output_file_id',
               existing_type=mysql.INTEGER(),
               comment='生成的文档文件ID',
               existing_nullable=True)
    op.alter_column('reports', 'generation_params',
               existing_type=mysql.JSON(),
               comment='生成参数',
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True,
               comment='生成状态',
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('reports', 'progress',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='生成进度（0-100）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('reports', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('reports', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment='生成完成时间',
               existing_nullable=True)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.alter_column('templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='模板名称',
               existing_nullable=False)
    op.alter_column('templates', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='模板描述',
               existing_nullable=True)
    op.alter_column('templates', 'file_id',
               existing_type=mysql.INTEGER(),
               comment='关联的文件ID',
               existing_nullable=True)
    op.alter_column('templates', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='创建者ID',
               existing_nullable=False)
    op.alter_column('templates', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='模板原始内容',
               existing_nullable=True)
    op.alter_column('templates', 'structure',
               existing_type=mysql.JSON(),
               comment='模板结构分析结果',
               existing_nullable=True)
    op.alter_column('templates', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True,
               comment='分析状态',
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('templates', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('templates', 'analyzed_at',
               existing_type=mysql.DATETIME(),
               comment='分析完成时间',
               existing_nullable=True)
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.alter_column('templates', 'analyzed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='分析完成时间',
               existing_nullable=True)
    op.alter_column('templates', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('templates', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False,
               comment=None,
               existing_comment='分析状态',
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('templates', 'structure',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='模板结构分析结果',
               existing_nullable=True)
    op.alter_column('templates', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='模板原始内容',
               existing_nullable=True)
    op.alter_column('templates', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('templates', 'file_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='关联的文件ID',
               existing_nullable=True)
    op.alter_column('templates', 'description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='模板描述',
               existing_nullable=True)
    op.alter_column('templates', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='模板名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.alter_column('reports', 'completed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='生成完成时间',
               existing_nullable=True)
    op.alter_column('reports', 'error_message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('reports', 'progress',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='生成进度（0-100）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('reports', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False,
               comment=None,
               existing_comment='生成状态',
               existing_server_default=sa.text("'PENDING'"))
    op.alter_column('reports', 'generation_params',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='生成参数',
               existing_nullable=True)
    op.alter_column('reports', 'output_file_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='生成的文档文件ID',
               existing_nullable=True)
    op.alter_column('reports', 'full_text',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='完整报告文本',
               existing_nullable=True)
    op.alter_column('reports', 'content',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='报告内容',
               existing_nullable=True)
    op.alter_column('reports', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='创建者ID',
               existing_nullable=False)
    op.alter_column('reports', 'data_file_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='数据文件ID',
               existing_nullable=True)
    op.alter_column('reports', 'template_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='使用的模板ID',
               existing_nullable=False)
    op.alter_column('reports', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='报告标题',
               existing_nullable=False)
    op.add_column('drafts', sa.Column('current_version_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drafts', sa.Column('editing_stage', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), server_default=sa.text("'draft'"), nullable=False))
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.create_foreign_key('drafts_ibfk_1', 'drafts', 'templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_drafts_current_version', 'drafts', 'draft_versions', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('drafts_ibfk_2', 'drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.create_index('ix_drafts_template_user', 'drafts', ['template_id', 'user_id'], unique=False)
    op.drop_column('drafts', 'is_current')
    op.drop_column('drafts', 'stage')
    op.drop_column('drafts', 'version')
    op.drop_column('drafts', 'format')
    op.drop_column('drafts', 'content')
    op.create_table('draft_versions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('draft_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('format', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), server_default=sa.text("'markdown'"), nullable=False),
    sa.Column('change_summary', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('word_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='draft_versions_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name='draft_versions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_draft_versions_version_number', 'draft_versions', ['draft_id', 'version_number'], unique=False)
    op.create_index('ix_draft_versions_draft_id', 'draft_versions', ['draft_id'], unique=False)
    # ### end Alembic commands ###